export type { AnalyticsEvent, IngestPayload, SdkInfo } from '@altitudems/analytics'
export { INGEST_SCHEMA_VERSION, isIngestPayload } from '@altitudems/analytics'

export type { AnalyticsStore, IngestMeta, StoredEvent } from './store'
export { MemoryStore } from './memory-store'
export type { CampaignStat, PageStat } from './memory-store'
export { createIngestHandler } from './ingest'
export type { IngestHandlerOptions } from './ingest'
export { registerDemoRoutes, registerIngest } from './hono'
export type { RegisterDemoRoutesOptions, RegisterIngestOptions } from './hono'
